# Generated by Django 3.1.3 on 2020-11-22 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_auto_20201122_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='link_downloaded',
        ),
        migrations.RemoveField(
            model_name='device',
            name='link_pending',
        ),
        migrations.RemoveField(
            model_name='device',
            name='link_received',
        ),
    ]
