# Generated by Django 3.1.3 on 2020-11-22 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('device', '0003_auto_20201122_0355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='link title')),
                ('url', models.TextField(verbose_name='download link')),
                ('status', models.CharField(choices=[('0', 'pending'), ('1', 'received'), ('2', 'downloaded')], default='0', max_length=1, verbose_name='link status')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dlink', to='device.device', verbose_name='device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ulink', to='accounts.user', verbose_name='user')),
            ],
            options={
                'verbose_name': 'link',
                'verbose_name_plural': 'links',
            },
        ),
    ]
